//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderConfig) DeepCopyInto(out *AIProviderConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderConfig.
func (in *AIProviderConfig) DeepCopy() *AIProviderConfig {
	if in == nil {
		return nil
	}
	out := new(AIProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoApproveConfig) DeepCopyInto(out *AutoApproveConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoApproveConfig.
func (in *AutoApproveConfig) DeepCopy() *AutoApproveConfig {
	if in == nil {
		return nil
	}
	out := new(AutoApproveConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoplanConfig) DeepCopyInto(out *AutoplanConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoplanConfig.
func (in *AutoplanConfig) DeepCopy() *AutoplanConfig {
	if in == nil {
		return nil
	}
	out := new(AutoplanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompatibilityPolicy) DeepCopyInto(out *CompatibilityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompatibilityPolicy.
func (in *CompatibilityPolicy) DeepCopy() *CompatibilityPolicy {
	if in == nil {
		return nil
	}
	out := new(CompatibilityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompatibilityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompatibilityPolicyList) DeepCopyInto(out *CompatibilityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CompatibilityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompatibilityPolicyList.
func (in *CompatibilityPolicyList) DeepCopy() *CompatibilityPolicyList {
	if in == nil {
		return nil
	}
	out := new(CompatibilityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompatibilityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompatibilityPolicySpec) DeepCopyInto(out *CompatibilityPolicySpec) {
	*out = *in
	if in.WatchNamespaces != nil {
		in, out := &in.WatchNamespaces, &out.WatchNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.AutoApprove = in.AutoApprove
	out.ScanInterval = in.ScanInterval
	in.AI.DeepCopyInto(&out.AI)
	if in.GitRepo != nil {
		in, out := &in.GitRepo, &out.GitRepo
		*out = new(GitRepoRef)
		(*in).DeepCopyInto(*out)
	}
	if in.TrackedTools != nil {
		in, out := &in.TrackedTools, &out.TrackedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Autoplan != nil {
		in, out := &in.Autoplan, &out.Autoplan
		*out = new(AutoplanConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompatibilityPolicySpec.
func (in *CompatibilityPolicySpec) DeepCopy() *CompatibilityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CompatibilityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompatibilityPolicyStatus) DeepCopyInto(out *CompatibilityPolicyStatus) {
	*out = *in
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]TrackedToolStatus, len(*in))
		copy(*out, *in)
	}
	if in.UntrackableTools != nil {
		in, out := &in.UntrackableTools, &out.UntrackableTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UnknownInstalled != nil {
		in, out := &in.UnknownInstalled, &out.UnknownInstalled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompatibilityPolicyStatus.
func (in *CompatibilityPolicyStatus) DeepCopy() *CompatibilityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CompatibilityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepoRef) DeepCopyInto(out *GitRepoRef) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepoRef.
func (in *GitRepoRef) DeepCopy() *GitRepoRef {
	if in == nil {
		return nil
	}
	out := new(GitRepoRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackUpgrade) DeepCopyInto(out *StackUpgrade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackUpgrade.
func (in *StackUpgrade) DeepCopy() *StackUpgrade {
	if in == nil {
		return nil
	}
	out := new(StackUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackUpgrade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackUpgradeList) DeepCopyInto(out *StackUpgradeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StackUpgrade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackUpgradeList.
func (in *StackUpgradeList) DeepCopy() *StackUpgradeList {
	if in == nil {
		return nil
	}
	out := new(StackUpgradeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackUpgradeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackUpgradeSpec) DeepCopyInto(out *StackUpgradeSpec) {
	*out = *in
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]ToolUpgradeSpec, len(*in))
		copy(*out, *in)
	}
	if in.GitRepo != nil {
		in, out := &in.GitRepo, &out.GitRepo
		*out = new(GitRepoRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackUpgradeSpec.
func (in *StackUpgradeSpec) DeepCopy() *StackUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(StackUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackUpgradeStatus) DeepCopyInto(out *StackUpgradeStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackUpgradeStatus.
func (in *StackUpgradeStatus) DeepCopy() *StackUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(StackUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolUpgradeSpec) DeepCopyInto(out *ToolUpgradeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolUpgradeSpec.
func (in *ToolUpgradeSpec) DeepCopy() *ToolUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(ToolUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackedToolStatus) DeepCopyInto(out *TrackedToolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackedToolStatus.
func (in *TrackedToolStatus) DeepCopy() *TrackedToolStatus {
	if in == nil {
		return nil
	}
	out := new(TrackedToolStatus)
	in.DeepCopyInto(out)
	return out
}
