//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all fields into out.
func (in *CompatibilityPolicy) DeepCopyInto(out *CompatibilityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy returns a deep copy of CompatibilityPolicy.
func (in *CompatibilityPolicy) DeepCopy() *CompatibilityPolicy {
	if in == nil {
		return nil
	}
	out := new(CompatibilityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CompatibilityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *CompatibilityPolicyList) DeepCopyInto(out *CompatibilityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CompatibilityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of CompatibilityPolicyList.
func (in *CompatibilityPolicyList) DeepCopy() *CompatibilityPolicyList {
	if in == nil {
		return nil
	}
	out := new(CompatibilityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CompatibilityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *CompatibilityPolicySpec) DeepCopyInto(out *CompatibilityPolicySpec) {
	*out = *in
}

// DeepCopy returns a deep copy of CompatibilityPolicySpec.
func (in *CompatibilityPolicySpec) DeepCopy() *CompatibilityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CompatibilityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *CompatibilityPolicyStatus) DeepCopyInto(out *CompatibilityPolicyStatus) {
	*out = *in
}

// DeepCopy returns a deep copy of CompatibilityPolicyStatus.
func (in *CompatibilityPolicyStatus) DeepCopy() *CompatibilityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CompatibilityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *StackUpgrade) DeepCopyInto(out *StackUpgrade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy returns a deep copy of StackUpgrade.
func (in *StackUpgrade) DeepCopy() *StackUpgrade {
	if in == nil {
		return nil
	}
	out := new(StackUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *StackUpgrade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *StackUpgradeList) DeepCopyInto(out *StackUpgradeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StackUpgrade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of StackUpgradeList.
func (in *StackUpgradeList) DeepCopy() *StackUpgradeList {
	if in == nil {
		return nil
	}
	out := new(StackUpgradeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *StackUpgradeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *StackUpgradeSpec) DeepCopyInto(out *StackUpgradeSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of StackUpgradeSpec.
func (in *StackUpgradeSpec) DeepCopy() *StackUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(StackUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *StackUpgradeStatus) DeepCopyInto(out *StackUpgradeStatus) {
	*out = *in
}

// DeepCopy returns a deep copy of StackUpgradeStatus.
func (in *StackUpgradeStatus) DeepCopy() *StackUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(StackUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}
